[build]
rustflags = ["-D", "warnings"]

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[target.aarch64-apple-darwin]
rustflags = ["-C", "link-arg=-fuse-ld=lld"]

[env]
RUST_BACKTRACE = "1"
RUST_LOG = "info"

# Performance optimizations for ExEx
[profile.release]
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = false

[profile.dev]
opt-level = 0
debug = true
panic = "unwind"
overflow-checks = true